### ISSUE TITLE
Can't connect to database from Authenticator class

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/FixedIt#1]
Stack Trace: 

```
java.sql.SQLNonTransientConnectionException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown Source)
	at fixedIt.sql.database.SQLWriter.executeSQL(SQLWriter.java:57)
	at fixedIt.sql.database.SQLWriter.executeDBCommand(SQLWriter.java:49)
	at fixedIt.modelComponents.Authenticator.addNewUserToDB(Authenticator.java:48)
	at tests.AddNewUserToDBTest.main(AddNewUserToDBTest.java:12)
Caused by: java.sql.SQLException: No current connection.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 11 more

```

**Comment by gghafir** [comment]
Potentially related to my issue?
On Mar 16, 2016 4:25 PM, "Mat Jones" <notifications@github.com> wrote:

> Stack Trace:
>
> java.sql.SQLNonTransientConnectionException: No current connection.
> at
> org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown
> Source)
> at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
> at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
> at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
> at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown Source)
> at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown
> Source)
> at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown
> Source)
> at fixedIt.sql.database.SQLWriter.executeSQL(SQLWriter.java:57)
> at fixedIt.sql.database.SQLWriter.executeDBCommand(SQLWriter.java:49)
> at
> fixedIt.modelComponents.Authenticator.addNewUserToDB(Authenticator.java:48)
> at tests.AddNewUserToDBTest.main(AddNewUserToDBTest.java:12)
> Caused by: java.sql.SQLException: No current connection.
> at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
> Source)
> at
> org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown
> Source)
> ... 11 more
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjones2014/FixedIt/issues/1>
>

-- 


This information is intended solely for the use of the individual to whom it is addressed. 
Any review, disclosure, copying, distribution or use of this e-mail communication by 
others is strictly prohibited.  If you are  not the intended recipient, please notify us 
immediately by returning  this message to the sender and delete all copies.

**Comment by mrjones2014** [comment]
nah, I've been having this for a few days now. No worries on your part.


*Matthew Jones*
*York College of Pennsylvania 2018*
*Computer Science*
mjones44@ycp.edu
215.527.9582

On Wed, Mar 16, 2016 at 4:28 PM, gghafir <notifications@github.com> wrote:

> Potentially related to my issue?
> On Mar 16, 2016 4:25 PM, "Mat Jones" <notifications@github.com> wrote:
>
> > Stack Trace:
> >
> > java.sql.SQLNonTransientConnectionException: No current connection.
> > at
> > org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown
> > Source)
> > at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
> > at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
> > at org.apache.derby.impl.jdbc.Util.noCurrentConnection(Unknown Source)
> > at org.apache.derby.impl.jdbc.EmbedConnection.checkIfClosed(Unknown
> Source)
> > at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown
> > Source)
> > at org.apache.derby.impl.jdbc.EmbedConnection.createStatement(Unknown
> > Source)
> > at fixedIt.sql.database.SQLWriter.executeSQL(SQLWriter.java:57)
> > at fixedIt.sql.database.SQLWriter.executeDBCommand(SQLWriter.java:49)
> > at
> >
> fixedIt.modelComponents.Authenticator.addNewUserToDB(Authenticator.java:48)
> > at tests.AddNewUserToDBTest.main(AddNewUserToDBTest.java:12)
> > Caused by: java.sql.SQLException: No current connection.
> > at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
> > Source)
> > at
> >
> org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown
> > Source)
> > ... 11 more
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mrjones2014/FixedIt/issues/1>
> >
>
> --
>
>
> This information is intended solely for the use of the individual to whom
> it is addressed.
> Any review, disclosure, copying, distribution or use of this e-mail
> communication by
> others is strictly prohibited. If you are not the intended recipient,
> please notify us
> immediately by returning this message to the sender and delete all copies.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjones2014/FixedIt/issues/1#issuecomment-197533950>
>

-- 


This information is intended solely for the use of the individual to whom it is addressed. 
Any review, disclosure, copying, distribution or use of this e-mail communication by 
others is strictly prohibited.  If you are  not the intended recipient, please notify us 
immediately by returning  this message to the sender and delete all copies.

**Comment by mrjones2014** [comment]
IT FINALLY WORKSSSSS!!!!!!!!!!!!!!!!!!
