### ISSUE TITLE
!!! SECURITY ISSUE !!!

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/FixedIt#11]
I just realized, with out implementation, using server-side cryptography, its possible that the passwords from the password field on the login web interface are being sent in plaintext, which, if not using an HTTPS (vs. just HTTP), is a huge vulnerability. NEED TO FIX ASAP, EVERYONE NEEDS TO HELP AND RESEARCH THIS.

Fixes include using an HTTPS connection, encrypt client-side with JavaScript then decrypt server-side and hash the decyrption, migrate all encryption to client-side*, etc.

\* I think this is **not** a good option; it exposes encryption/decryption logic to the client (and therefore potential attackers), and as far as I know (I could be wrong) it's less secure under most circumstances. See [this answer](http://stackoverflow.com/a/21716654) on StackOverflow for a pretty good explanation of this.

**Comment by gghafir** [comment]
** Most likely solution: encrypt client-side and make the server do the decryption.

**Comment by mrjones2014** [comment]
Professor Hake said don't worry about it for this project since it only matters if it's going on an internet server. Should be a relatively easy fix anyway. If we move forward with the project beyond the course, Professor Hake suggested we seek advice from Dr. Hovemeyer on this issue.
