### ISSUE TITLE
5HUI7 BR0K3 3V3RYWH3R3

### ISSUE THREAD

**Issue by YoungMaker** [mrjones2014/FixedIt#22]
Wh3n I 7ri3d 70 10gin i7 br0k3 my 3 k3y n0w I h@v3 70 7yp3 3 in573@d 0f 3. 

Wh3n I 10gg3d inu n37f1;ixx i7 wh3n7 @11 1ik3 bruh idkkk i7 gu57 kind@ w3n7 K@B1000WY kj1gfd5jk1fg 50 7hi5 5ch3duk13 7hing1y I 7ri3d 

I h@v3 b33n r3qu3573d by 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny 70 c0n7@c7 y0u f0r @55i57@nc3 in r3501ving @ m@773r. 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny h@5 r3c3n71y c0nc1ud3d @ 1@rg3 numb3r 0f c0n7r@c75 f0r 0i1 3xp10r@7i0n in 7h3 5ub-5@h@r@ r3gi0n. 7h3 c0n7r@c75 h@v3 imm3di@731y pr0duc3d m0n3y5 3qu@1ing U5$40,000,000. 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny i5 d35ir0u5 0f 0i1 3xp10r@7i0n in 07h3r p@r75 0f 7h3 w0r1d, h0w3v3r, b3c@u53 0f c3r7@in r3gu1@7i0n5 0f 7h3 Nig3ri@n G0v3rnm3n7, i7 i5 un@b13 70 m0v3 7h353 fund5 70 @n07h3r r3gi0n.

Y0u @55i57@nc3 i5 r3qu3573d @5 @ n0n-Nig3ri@n ci7iz3n 70 @55i57 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny, @nd @150 7h3 C3n7r@1 B@nk 0f Nig3ri@, in m0ving 7h353 fund5 0u7 0f Nig3ri@. If 7h3 fund5 c@n b3 7r@n5f3rr3d 70 y0ur n@m3, in y0ur Uni73d 57@735 @cc0un7, 7h3n y0u c@n f0rw@rd 7h3 fund5 @5 dir3c73d by 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny. In 3xch@ng3 f0r y0ur @cc0mm0d@7ing 53rvic35, 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny w0u1d @gr33 70 @110w y0u 70 r37@in 10%, 0r U5$4 mi11i0n 0f 7hi5 @m0un7.

H0w3v3r, 70 b3 @ 13gi7im@73 7r@n5f3r33 0f 7h353 m0n3y5 @cc0rding 70 Nig3ri@n 1@w, y0u mu57 pr353n71y b3 @ d3p05i70r 0f @7 13@57 U5$100,000 in @ Nig3ri@n b@nk which i5 r3gu1@73d by 7h3 C3n7r@1 B@nk 0f Nig3ri@.

If i7 wi11 b3 p055ib13 f0r y0u 70 @55i57 u5, w3 w0u1d b3 m057 gr@73fu1. W3 5ugg357 7h@7 y0u m337 wi7h u5 in p3r50n in 1@g05, @nd 7h@7 during y0ur vi5i7 I in7r0duc3 y0u 70 7h3 r3pr353n7@7iv35 0f 7h3 Nig3ri@n N@7i0n@1 P37r013um C0mp@ny, @5 w311 @5 wi7h c3r7@in 0ffici@15 0f 7h3 C3n7r@1 B@nk 0f Nig3ri@.

P13@53 c@11 m3 @7 y0ur 3@r1i357 c0nv3ni3nc3 @7 18-467-4975. 7im3 i5 0f 7h3 3553nc3 in 7hi5 m@773r; v3ry quick1y 7h3 Nig3ri@n G0v3rnm3n7 wi11 r3@1iz3 7h@7 7h3 C3n7r@1 B@nk i5 m@in7@ining 7hi5 @m0un7 0n d3p05i7, @nd @773mp7 70 13vy c3r7@in d3p05i70ry 7@x35 0n i7.

✋🐸✋🐸✋🐸✋🐸 0 5hi7 w@ddup 👋 h3r3 🚲 c0m3 d@7 bଠi🚲🚲 righ7🚲🚲7h 🐸 3r3✋✋✋ d@7 🐸 b0i ✔🐸 ✔if d@7 b0i 🐸  ƽ@i 50 💯 i 5@i 50 💯 7h@75 wh@7 im 7@1king @b0u7 righ7 7h3r3 🚲 0 5hi7 (ch0ru5: ଠ 5ʰᶦᵗ) mMMMMᎷМ💯 ✋✋00ОଠＯ00Ｏ0Оଠଠ0000ᵒᵒᵒᵒᵒᵒᵒᵒᵒ✋ ✋ ✋ ✋ 💯 🐸🐸🐸 👋👋 w@ddup

**Comment by FixedItWebMaster** [comment]
w@ddup d00d n1c3 c0mm3nt m8 th@nk5 4 y0r 1nput br0
