### ISSUE TITLE
Implement multiple schedules per user

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/FixedIt#4]
Tips/Ideas:
1. On "view schedule" jsp, have user select which schedule to view from a dropdown
2. On "search" jsp and servlet, have "add to schedule" button bring up a popup to select which schedule to add course to
3. Alternatively, could implement "Active Schedule" feature; added courses would automatically be added to the "Active Schedule"; change the "Active Schedule" via a dropdown list on the "search" jsp

Classes/Methods that need to be updated to implement this include but are not limited to:
1. Search.jsp
2. QueryController (add Schedule as a field; this will be the active schedule; be sure to update constructors; also, addToSchedule method adds to "testSchedule" by default. Change this)
3. SearchServlet - Particularly the following code snippet (line ~108)
```
if(req.getParameter("" + c.getCRN())!=null){
	boolean success=controller.addToSchedule(c.getCRN());
	if(success){
		System.out.println("Course added successfully.");
		errorMessage="Course added successfully";
	}
	else{
		errorMessage="Course conflicts with one on schedule, or something went wrong.";
	}
}
```

**Comment by mrjones2014** [comment]
@gghafir, we should both work on this together; it requires updating code that originates from each of us. Something to note, I think issue #12 (schedule ghosting) should be fixed first.

Classes that need to be updated:
- [ ] SearchServlet
- [ ] QueryController
- [ ] DisplayScheduleServlet
- [ ] AccountInfoServlet (for viewing list of schedules, or selecting "Active" schedule, if we choose to go with that implementation)

Possibly more.

**Comment by gghafir** [comment]
Sounds good! Will be a ton of fun to solve haha

**Comment by mrjones2014** [comment]
@gghafir I'll work on this with you since I implemented the single schedule and this will be a lot of retracing my steps from that.

**Comment by gghafir** [comment]
Sounds good. Shouldn't be awful. Just going to be a lot of small changes

**Comment by mrjones2014** [comment]
- [ ] Add "New Schedule" button to My Account page
- [ ] Restyle select box on My Account page
- [ ] Add submit button for Active Schedule selector on My Account page
- [ ] Change how schedules are accessed in DisplayScheduleServlet (access by schedule name)
- [ ] Change how schedules are accessed in SearchServlet (access by schedule name)
- [ ] Change how schedules are accessed in QueryController (access by schedule name)
- [ ] Change how schedules are accessed in DisplayScheduleController (access by schedule name)

**Comment by mrjones2014** [comment]
Implemented and tested.
