### ISSUE TITLE
Add a "debug mode" to the web interface

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/FixedIt#6]
This "debug" mode could just auto-login to a dummy account without asking for user credentials, and should be somewhat hidden in some way (i.e. put it at the bottom of the home page, off screen by default or something similar). It'll just make everyone's lives easier when trying to test and debug stuff.

Keep in mind, since the database does not get synced with git, this "debug mode" should also be able to create the dummy account if it doesn't already exist on your version of the database. Don't bother with authentication for the dummy account; just create a session right away.

**Comment by mskur1** [comment]
debug mode is implemented and works properly. You are able to log into a fakeuser account to debug the application, you are still able to log out and into a personal account that is specific to a user.
