### ISSUE TITLE
Properly implement "edit account" servlet/jsp; make persistent

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/FixedIt#7]
Should be able to edit student status and email address; updating password should also be implemented but needs to be more carefully designed.

Maybe password update should have its own separate servlet/jsp? It would need the following fields:
1. Old password
2. New password
3. Confirm new password
4. Maybe a reCAPTCHA?

**Comment by gghafir** [comment]
Password update should definitely have its own servlet/jsp due to the severity of the change. Email address change should also require a re-prompt of the current password

**Comment by gghafir** [comment]
passwordUpdate will need a method to implement the actual change. For now, it will make sure that the new passwords match, the old password was entered correctly, and that the new password is valid.

**Comment by gghafir** [comment]
passwordUpdate is now working. Need email to be working
